### ISSUE TITLE
Tim sort algorithm is incorrect.

### ISSUE THREAD

**Issue by abdavis** [mszula/visual-sorting#4]
The tim sort algorithm is wrong. It's easiest to see how it's wrong with the valley input. A proper Tim sort implementation recognizes the descending run and flips it, then discovers the second already sorted run, and does one merge to finalize.

**Comment by mszula** [comment]
Hey, thx for discover. I will check that soon.

**Comment by maciejmaczko** [comment]
@abdavis Well spotted! How do you like my [improvements](https://github.com/mszula/visual-sorting/pull/10)?

**Comment by mszula** [comment]
Should work properly now, closing the thread.
